Add additional costs field in `EthereumTransactionBody`
hashgraph/hedera-protobufs pull request #255
Opened 2023-01-24 14:22 UTC by dimitar-dinev

**Description**:

**Related issue(s)**:

Fixes #254

2023-01-24 15:31 UTC, dimitar-dinev commented on services/ethereum_transaction.proto
> +   * is willing to pay to for any additional *non-gas* costs of the transaction.
Fixed

2023-01-24 15:33 UTC, dimitar-dinev commented on services/ethereum_transaction.proto
> +  int64 max_additional_costs_allowance = 4;
Yup,  `max_additional_fee_allowance` is clearer IMO, changed now

2023-01-24 17:32 UTC, Neeharika-Sompalli approved these changes
LGTM !

2023-01-30 17:22 UTC, david-bakin-sl approved these changes
LGTM

2023-02-01 13:14 UTC, Nana-EC requested changes
Blocking as we may not need this any longer.

2023-02-02 08:32 UTC, dimitar-dinev commented
Closing this as a different fee-charging strategy involving multiple gas prices was chosen, and these changes are no longer needed.

2023-02-02 08:32 UTC, closed without merging