update account ids
hashgraph/hedera-protobufs pull request #291
Opened 2023-06-29 20:04 UTC by kimbor

Update account.proto to use IDs instead of longs

**Related issue(s)**:
[Issue #7243 in hedera-services ](https://github.com/hashgraph/hedera-services/issues/7243)

2023-06-30 18:49 UTC, jsync-swirlds approved these changes

2023-07-14 22:27 UTC, rbair23 approved these changes

2023-07-17 15:24 UTC, iwsimon approved these changes
LGTM

2023-07-19 20:19 UTC, jsync-swirlds commented on services/state/schedule/schedule.proto
This reverts a change recently merged.  Please undo changes to this file.

2023-07-19 20:22 UTC, jsync-swirlds commented on services/state/token/network_staking_rewards.proto
Is deleting this file intentional?
Both of the changes in "resolve conflicts" appear to undo changes from others.

2023-07-19 20:23 UTC, jsync-swirlds requested changes
Please address the issues raised by the commit that resolved conflicts.

2023-07-19 21:06 UTC, kimbor commented on services/state/schedule/schedule.proto
Yep. Fixed.

2023-07-19 21:07 UTC, kimbor commented on services/state/token/network_staking_rewards.proto
No, it was not intentional. I've reverted the deletion.

2023-07-19 21:08 UTC, jsync-swirlds approved these changes

2023-07-20 17:09 UTC, merged