feat: HIP-904 maxAutoAssociations updates and token reject transaction
hashgraph/hedera-protobufs pull request #348
Opened 2024-05-08 16:08 UTC by MiroslavGatsanoga

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-05-08 16:55 UTC, Nana-EC requested changes
Some unexpected files are present in the PR.
This should be limted to automaxassocaitions and TokenReject

2024-05-08 16:56 UTC, Neeharika-Sompalli commented
> Some unexpected files are present in the PR. This should be limted to automaxassocaitions and TokenReject

yes @Nana-EC . Once it is synced back with base branch they should be resolved

2024-05-09 12:01 UTC, Nana-EC submitted a review, later dismissed

2024-05-09 13:36 UTC, netopyr commented
We plan to implement the changes for maxAutoAssociations only in the upcoming release. The protobuf modifications need to be limited accordingly.

2024-05-09 15:15 UTC, Neeharika-Sompalli submitted a review, later dismissed
LGTM! Thanks @MiroslavGatsanoga

2024-05-09 15:15 UTC, Neeharika-Sompalli commented on services/response_code.proto
> +
May be this is not needed for this release ?

2024-05-09 15:17 UTC, Neeharika-Sompalli commented on services/crypto_create.proto
> +     * By default this value is 0 for accounts except for auto-created accounts which default -1.
And these documentations, since @netopyr  mentioned `maxAutoAssociations` are pushed to next release.

2024-05-13 08:38 UTC, netopyr requested changes
Please reduce this PR to changes that are required for release 0.51.

2024-05-13 15:19 UTC, jsync-swirlds approved these changes

2024-05-13 16:11 UTC, Nana-EC approved these changes

2024-05-14 08:27 UTC, netopyr approved these changes
LGTM

2024-05-14 14:10 UTC, merged