Reserve removed fields to preserve SDK compatibility
hashgraph/hedera-protobufs pull request #352
Opened 2024-05-15 19:45 UTC by jsync-swirlds

Several fields were removed from protobuf without reserving the field numbers.
Some of these removals are temporary, others are permanent.
Here we reserve the field numbers for those removed fields to ensure the field numbers are not accidentally reused, breaking compatibility.

2024-05-15 20:11 UTC, mhess-swl commented on services/basic_types.proto
> +    //     into the single immutable alias field.
This gap looks intentional, yes?

2024-05-15 20:12 UTC, mhess-swl approved these changes
LGTM. Thanks @jsync-swirlds !

2024-05-15 20:39 UTC, jsync-swirlds commented on services/basic_types.proto
> +    //     into the single immutable alias field.
Yes, it's there to improve readability.

2024-05-15 21:37 UTC, steven-sheehy reviewed
Why do we need to reserve fields for HIPs that never made it to any environment? HIPs 583/631 virtual addresses was removed in favor of a different approach and is not expected to come back. Likewise the autorenew fields never made it to production. The only reason we would need to reserve them is if there is data in any bucket that might have these fields present, which is not the case. If this functionality is ever resurrected we can assign them whatever is the newest field number at the time.

2024-05-15 21:48 UTC, jsync-swirlds commented
> Why do we need to reserve fields for HIPs that never made it to any environment? HIPs 583/631 virtual addresses was removed in favor of a different approach and is not expected to come back. Likewise the autorenew fields never made it to production. The only reason we would need to reserve them is if there is data in any bucket that might have these fields present, which is not the case. If this functionality is ever resurrected we can assign them whatever is the newest field number at the time.

Those versions were published on the main branch, so external code may have been built with them, and we cannot, as far as I know, guarantee nothing was serialized with those definitions.  Once anything is serialized with a definition, the field number _must not_ be reused with a different type definition, it breaks compatibility.

If we have clear evidence that there is _no chance_ that the definition with those fields included was ever used, we can drop the reserved, but currently I am not aware of such.  The safe option, then, is to reserve the field numbers and either restore the fields exactly as originally defined, or just not use those numbers going forward.

Reserving a field number doesn't hurt us in any significant manner, and avoids any possibility of serialization errors due to reusing field numbers with a different definition.

2024-05-15 23:36 UTC, steven-sheehy requested changes
> If we have clear evidence that there is no chance that the definition with those fields included was ever used, we can drop the reserved, but currently I am not aware of such. The safe option, then, is to reserve the field numbers and either restore the fields exactly as originally defined, or just not use those numbers going forward.

We do know 100% that it didn't get serialized and make its way into any bucket.

> Reserving a field number doesn't hurt us in any significant manner, and avoids any possibility of serialization errors due to reusing field numbers with a different definition.

It bloats the protobuf definition unnecessarily and somewhat defeats the purpose of removing those changes before they made it into an artifact. It may not functionally cause any harm but it makes the API less clear and concise. As such I am against this change without explicit proof this is causing customer's any harm.

2024-05-15 23:57 UTC, jsync-swirlds commented
> > If we have clear evidence that there is no chance that the definition with those fields included was ever used, we can drop the reserved, but currently I am not aware of such. The safe option, then, is to reserve the field numbers and either restore the fields exactly as originally defined, or just not use those numbers going forward.
> 
> We do know 100% that it didn't get serialized and make its way into any bucket.

If we're certain these changes never made it into a third-party SDK nor were ever used submit transactions ("buckets" are only part of the picture, not everything), then I'm fine with documenting that and moving on.  The purpose of this PR is that we had a _public_ version (which means we don't control if or how it's used) of the codebase that included fields that were later removed without any clear documentation of what was done or why (and when discovered, nobody involved could remember why things were removed).

I'll close this PR based on your statements, and document the original removal PR with the claims presented.

2024-05-16 00:06 UTC, jsync-swirlds commented
As claimed above, that despite being on the main branch for 4-6 months, the versions of these proto files with the removed fields were never used in any deployed software (regardless of whether the individual fields were filled in).

Closing as unnecessary based on that assertion.

2024-05-16 00:06 UTC, closed without merging