chore: Rename payload to transaction
hashgraph/hedera-protobufs pull request #401
Opened 2024-07-30 16:29 UTC by timo0

Part of #14000

2024-07-30 16:46 UTC, jsync-swirlds approved these changes
Looks Good.  Only minor editing nitpicks.

2024-07-30 16:46 UTC, jsync-swirlds commented on platform/event/event_descriptor.proto
> +   * 2. The SHA-384 hash of each individual `EventTransaction`, in the order the transactions appear in the `event_transactions` field of the `GossipEvent` protobuf
nit: This line is a bit long.  Ideally we'd wrap these comments at about 80 characters.

2024-07-31 08:17 UTC, lpetrovic05 approved these changes

2024-07-31 08:18 UTC, lpetrovic05 requested changes
Looks good, but must not be merged before the hedera repo gets updated, so blocking it

2024-07-31 15:36 UTC, lpetrovic05 approved these changes

2024-07-31 15:36 UTC, merged