ci: Update CODEOWNERS file
hashgraph/hedera-protobufs pull request #459
Opened 2024-12-13 08:28 UTC by mishomihov00

**Description**:

Updates the CODEOWNERS file

**Related issue(s)**:

Fixes #456 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-12-13 09:37 UTC, san-est approved these changes
LGTM

2024-12-13 15:03 UTC, andrewb1269hg submitted a review, later dismissed

2024-12-13 15:27 UTC, rbarkerSL requested changes

2024-12-13 15:27 UTC, rbarkerSL commented on .github/CODEOWNERS
> +/.github/workflows/                             @hashgraph/devops-ci
```suggestion
/.github/workflows/                             @hashgraph/devops-ci @hashgraph/devops-ci-committers @hashgraph/release-engineering-managers 
```

2024-12-13 15:27 UTC, rbarkerSL commented on .github/CODEOWNERS
> +/README.md                                      @hashgraph/release-engineering-managers @hashgraph/devops-ci
```suggestion
/README.md                                      @hashgraph/devops-ci @hashgraph/release-engineering-managers @hashgraph/developer-advocates @hashgraph/platform-base @hashgraph/hedera-services @hashgraph/mirror-node @hashgraph/hedera-smart-contracts @hashgraph/block-node
```

2024-12-13 15:27 UTC, rbarkerSL commented on .github/CODEOWNERS
> +**/.gitignore.*                                 @hashgraph/release-engineering-managers @hashgraph/devops-ci
```suggestion
**/.gitignore                                   @hashgraph/devops-ci @hashgraph/release-engineering-managers @hashgraph/developer-advocates @hashgraph/platform-base @hashgraph/hedera-services @hashgraph/mirror-node @hashgraph/hedera-smart-contracts @hashgraph/block-node
**/.gitignore.*                                 @hashgraph/devops-ci @hashgraph/release-engineering-managers @hashgraph/developer-advocates @hashgraph/platform-base @hashgraph/hedera-services @hashgraph/mirror-node @hashgraph/hedera-smart-contracts @hashgraph/block-node
```

2024-12-13 17:55 UTC, jsync-swirlds commented on .github/CODEOWNERS
> +#Platform and mirror folder rules
We might consider adding the following specific rules:
```
# Block Node Folder Rules
/block/                                           @hashgraph/block-node @hashgraph/hedera-services @hashgraph/mirror-node
/services/                                        @hashgraph/hedera-services @hashgraph/mirror-node
```

2024-12-16 13:48 UTC, andrewb1269hg approved these changes

2024-12-16 15:20 UTC, jsync-swirlds approved these changes

2024-12-16 17:55 UTC, rbarkerSL approved these changes

2024-12-17 07:53 UTC, merged